# -*- coding: utf-8 -*-
#-*- author: Wale Yu              -*-
#-*- update: 2023.5.21              -*-
#-*- email:  chuanqi_yu2021@126.com -*-

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1500, 1200)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout.addWidget(self.groupBox, 0, 0, 2, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout.addWidget(self.groupBox_2, 2, 0, 2, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout.addWidget(self.groupBox_3, 2, 1, 2, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout.addWidget(self.groupBox_4, 0, 1, 2, 1)
        self.gridLayout.setColumnStretch(0, 1)
        self.gridLayout.setColumnStretch(1, 1)
        self.gridLayout.setRowStretch(0, 1)
        self.gridLayout.setRowStretch(1, 1)
        self.gridLayout.setRowStretch(2, 1)
        self.gridLayout.setRowStretch(3, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1500, 24))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionpreference = QtWidgets.QMenu(self.menuEdit)
        self.actionpreference.setObjectName("actionpreference")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.action_Dark = QtWidgets.QAction(MainWindow)
        self.action_Dark.setObjectName("action_Dark")
        self.action_Light = QtWidgets.QAction(MainWindow)
        self.action_Light.setObjectName("action_Light")
        self.action_Blue = QtWidgets.QAction(MainWindow)
        self.action_Blue.setObjectName("action_Blue")
        self.action_Indigo = QtWidgets.QAction(MainWindow)
        self.action_Indigo.setObjectName("action_Indigo")
        self.action_Original = QtWidgets.QAction(MainWindow)
        self.action_Original.setObjectName("action_Original")
        self.actionUser_manual = QtWidgets.QAction(MainWindow)
        self.actionUser_manual.setObjectName("actionUser_manual")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionpreference.addAction(self.action_Original)
        self.actionpreference.addAction(self.action_Dark)
        self.actionpreference.addAction(self.action_Blue)
        self.actionpreference.addAction(self.action_Light)
        self.actionpreference.addAction(self.action_Indigo)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuEdit.addAction(self.actionpreference.menuAction())
        self.menuHelp.addAction(self.actionUser_manual)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "WTG-Risk-Control"))
        self.groupBox.setTitle(_translate("MainWindow", "Chart avg_u"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Chart avg_v"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Chart avg_u_Fourier"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Chart feature_matching"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionOpen.setText(_translate("MainWindow", "Input"))
        self.actionpreference.setTitle(_translate("MainWindow", "Preference"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.action_Dark.setText(_translate("MainWindow", "Dark-LightGreen Theme"))
        self.action_Blue.setText(_translate("MainWindow","Dark-Cyan Theme"))
        self.action_Light.setText(_translate("MainWindow","Light-Blue Theme"))
        self.action_Indigo.setText(_translate("MainWindow","Light-Orange Theme"))
        self.action_Original.setText(_translate("MainWindow","Original Theme"))
        self.actionUser_manual.setText(_translate("MainWindow", "User-manual"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(600, 480)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 3, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 2, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 3, 0, 1, 1)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setText("")
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(False)
        self.label.setOpenExternalLinks(False)
        self.label.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 0, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 3, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setTextFormat(QtCore.Qt.AutoText)
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 1, 3, 2)
        self.gridLayout.setColumnStretch(0, 1)
        self.gridLayout.setColumnStretch(1, 2)
        self.gridLayout.setColumnStretch(2, 1)
        self.gridLayout.setRowStretch(0, 2)
        self.gridLayout.setRowStretch(1, 2)
        self.gridLayout.setRowStretch(2, 2)
        self.gridLayout.setRowStretch(3, 1)
        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "About WTG-Risk-Control"))
        self.pushButton.setText(_translate("Dialog", "Close"))
        self.label_2.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">WTG-Risk-Control</span></p><p><br/></p><p><span style=\" font-size:8pt;\">Version: v 1.1.0</span></p><p><span style=\" font-size:8pt;\">WTG-Risk-Control is a software used for monitoring and analyzing wind </span></p><p><span style=\" font-size:8pt;\">turbine tower damage detection.</span></p><p><span style=\" font-size:8pt;\">The programming language used for WTG-Risk-Control is Python,and the</span></p><p><span style=\" font-size:8pt;\">interface is developed based on the PyQt5 framework.The image processing</span></p><p><span style=\" font-size:8pt;\">is carried out using OpenCV library.</span></p><p><span style=\" font-size:8pt;\">WTG-Risk-Control was developed by Huangxingjian,Yuchuanqi and Pengjunming.</span></p><p><span style=\" font-size:8pt;\">Yuchuanqi was responsible for interface design and software</span></p><p><span style=\" font-size:8pt;\">production,while Huangxingjian and Pengjunming were responsible for </span></p><p><span style=\" font-size:8pt;\">the calculation and logical processing.</span></p><p><br/></p><p><span style=\" font-size:10pt; font-weight:600;\">Thank you for using WTG-Risk-Control!</span></p><p><span style=\" font-size:10pt; font-weight:600;\">We hope you can provide valuable feedback for improvement!</span></p><p><span style=\" font-size:10pt; font-weight:600;\">Email:Xingjian_Huang@outlook.com,chuanqi_yu2021@126.com</span></p></body></html>"))
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
